.MODEL SMALL
.STACK 100H
.DATA
STR DB 100 DUP('$')
INPUT_MSG1 DB 'ENTER YOUR STRING: $'
OUTPUT_MSG_FOR_VOWELS DB 'NUMBER OF VOWELS: $'
OUTPUT_MSG_FOR_CONSONENTS DB 'NUMBER OF CONSONENTS: $'
OUTPUT_MSG_FOR_DIGITS DB 'NUMBER OF DIGITS: $'
OUTPUT_MSG_FOR_SPACE DB 'NUMBER OF SPACE: $'
VOWELS DB 'AEIOUaeiou'
N DW 0H
VC DW 0H
CC DW 0H
DC DW 0H
SC DW 0H

.CODE

MAIN PROC

    MOV AX,@DATA
    MOV DS,AX

    ;SHOW INPUT PROMPT
    MOV AH,9
    LEA DX,INPUT_MSG1
    INT 21H

    XOR SI,SI
    ; MOV N,0
    MOV AH,1
    INPUT:
        INT 21H
        CMP AL,0DH
        JE EXIT_FROM_INPUT
        ; MOV STR[SI],AL

        CMP AL,'A'
        JL NOT_A_CHARACTER
        CMP AL,'Z'
        JL CHECK_FOR_VC

        CMP AL,'a'
        JL NOT_A_CHARACTER
        CMP AL,'z'
        JG NOT_A_CHARACTER

        CHECK_FOR_VC:
        MOV CX,10
        XOR SI,SI
        CHECK_VOWEL:
            CMP AL,VOWELS[SI] 
            JE FIND_VOWEL
            
            INC SI
        LOOP CHECK_VOWEL
        JMP FIND_CONSONENT
        FIND_VOWEL:
            INC VC
            JMP COMPLETE_CHECKING_FOR_AL
        FIND_CONSONENT:
            INC CC
            JMP COMPLETE_CHECKING_FOR_AL

        NOT_A_CHARACTER:

        CMP AL,' '
        JE FIND_SPACE
        CMP AL,'0'
        JL COMPLETE_CHECKING_FOR_AL
        CMP AL,'9'
        JG COMPLETE_CHECKING_FOR_AL
        JMP FIND_DIGIT
        FIND_SPACE:
            INC SC
            JMP COMPLETE_CHECKING_FOR_AL
        FIND_DIGIT:
            INC DC
            JMP COMPLETE_CHECKING_FOR_AL

        COMPLETE_CHECKING_FOR_AL:
        ; INC SI
    JMP INPUT
    EXIT_FROM_INPUT:

    MOV N,SI ; N WILL STORE THE INPUT STRING SIZE
    CALL PRINT_NEW_LINE
    ; SHOW OUTPUT MSG FOR VOWELS
    MOV AH,9
    LEA DX,OUTPUT_MSG_FOR_VOWELS
    INT 21H
    MOV AH,2
    ADD VC,30H
    MOV DX,VC
    INT 21H

    CALL PRINT_NEW_LINE

    ;SHOW OUTPUT FOR CONSONENTS
    MOV AH,9
    LEA DX,OUTPUT_MSG_FOR_CONSONENTS
    INT 21H
    MOV AH,2
    ADD CC,30H
    MOV DX,CC
    INT 21H

    CALL PRINT_NEW_LINE

    ;SHOW OUTPUT FOR SPACE
    MOV AH,9
    LEA DX,OUTPUT_MSG_FOR_SPACE
    INT 21H
    MOV AH,2
    ADD SC,30H
    MOV DX,SC
    INT 21H

    CALL PRINT_NEW_LINE

    ;SHOW OUTPUT FOR DIGITS
    MOV AH,9
    LEA DX,OUTPUT_MSG_FOR_DIGITS
    INT 21H
    MOV AH,2
    ADD DC,30H
    MOV DX,DC
    INT 21H


    ;END OF MAIN 
    MOV AH,4CH
    INT 21H

MAIN ENDP
PRINT_NEW_LINE PROC
    MOV AH,2
    MOV DL,0AH
    INT 21H
    MOV DL,0DH
    INT 21H
    RET
PRINT_NEW_LINE ENDP

END MAIN